# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
