# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-28 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191026_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='picture/')),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='title', max_length=100, null=True)),
                ('description', models.TextField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='picture/')),
            ],
        ),
    ]
